name: pakan_ikan
description: Automatic Fish Feeder – Flutter (iOS + Android)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1          # Used for Firebase Realtime Database REST API calls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  ios: true
  image_path: "assets/icon.png"